services:
  astro-pages:
    container_name: astro-pages
    image: misakanetworks-frontend:${HOST_TYPE:-latest}
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    restart: always
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge